#
# Make sure these containers sync up with local conf file
#
# - MySQL    : https://hub.docker.com/_/mysql
# - RabbitMQ : https://hub.docker.com/_/rabbitmq

version: '2.0'
services:

  master:
    build: .
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/run:/run:rw'
      - '/lib/modules:/lib/modules:rw'
      - '/tmp:/tmp:rw'
      - './src:/opt'
    links:
      - mysql
      - rabbit
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'
      - '8080:8080'
    working_dir: '/opt'
    environment:
      DEBUG: 'true'
      TERM:  'xterm'

  mysql:
    image: mysql:latest
    expose:
      - '5432'
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'

  rabbit:
    image: rabbitmq:latest
    expose:
      - '8080'
      - '15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'user' 
      RABBITMQ_DEFAULT_PASS: 'pass'