---
- name: Cleans up ssh config and directories
  
  hosts: 127.0.0.1
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"

  sudo: true

  vars:

    ip:   "{{ lookup('env', 'VD_ENV_GUEST_IP')        }}"
    key:  "{{ lookup('env', 'VD_ENV_DEFAULT_RSA_KEY') }}"
    host: "{{ lookup('env', 'VD_ENV_HOSTNAME')        }}"

    workspace:   "{{ lookup('env', 'VD_ENV_WORKSPACE')       }}"
    ssh_config:  "{{ lookup('env', 'VD_ENV_SSH_CONFIG')      }}"
    known_hosts: "{{ lookup('env', 'VD_ENV_SSH_KNOWN_HOSTS') }}"

  tasks:

    - name: Remove .env file 
      file: path="{{ workspace }}/.env"
            state=absent 
    
    - name: "Unmount directories in {{ workspace }}"
      shell: "fusermount -u {{ workspace }}/{{ item }}"
      with_items:
        - devstack
        - stack
      ignore_errors: yes

    - name: "Ensure '{{ known_hosts }}' is clean"
      lineinfile: dest="{{ known_hosts }}" 
                  regexp="^({{ ip }}|{{ host }})"
                  state=absent

    - name: "Remove '{{ host }}' config to '{{ ssh_config }}'"
      blockinfile:
        dest: "{{ ssh_config }}"
        block: |
          Host {{ host }}                          
            Hostname     {{ ip }}            
            User         stack
            IdentityFile {{ key }}
            StrictHostKeyChecking no
        state: absent
