---
- name: Cleans up ssh config and directories
  
  hosts: 127.0.0.1
  connection: local

  vars:
    workspace: "{{ lookup('env', 'WORKSPACE') }}"

  tasks:

    - name: "Remove directories" 
      file: path="{{ workspace }}/{{ item }}"
            state=absent
      with_items:
        - devstack
        - src
      become: yes
      become_user: root
