---
- name: Run the Devstack Container as a daemon

  hosts: 127.0.0.1
  connection: local

  vars:

    user:      "{{ lookup('env', 'USER')          }}"
    workspace: "{{ lookup('env', 'WORKSPACE')     }}"
    cgrp_vol:  "{{ lookup('env', 'CGROUP_VOL')    }}"
    # run_vol:   "{{ lookup('env', 'RUN_VOL')       }}"
    # lib_vol:   "{{ lookup('env', 'LIB_VOL')       }}"
    dstk_vol:  "{{ lookup('env', 'DEVSTACK_VOL')  }}"
    dstk_port: "{{ lookup('env', 'DEVSTACK_PORT') }}"

    dstk_img:       "{{ lookup('env', 'DEVSTACK_IMG')       }}"
    dstk_container: "{{ lookup('env', 'DEVSTACK_CONTAINER') }}"

  tasks:
    
    - name: Run the devstack container as the stack user in the container
      shell: "docker run -d
                         --privileged
                         --net=host 
                         -p {{ dstk_port }}
                         -v {{ cgrp_vol  }}
                         -v {{ dstk_vol  }}
                         --name {{ dstk_container }} {{ dstk_img }}"
      become: yes
    #   become_user: "{{ user }}"

    # - name: RDeploy... The Stack of Dev 
    #   shell: "docker-compose up -d"
    #   become: yes
    #   become_user: "{{ user }}"

                        # -v {{ run_vol   }}
                         # -v {{ lib_vol   }}
