---
- name: Play that provisions the guest VM environment for devstack
  
  hosts: guests
  remote_user: root

  vars:

    user:      "{{ lookup('env', 'USER') }}"
    key:       "{{ lookup('env', 'VD_ENV_DEFAULT_RSA_KEY') }}"
    workspace: "{{ lookup('env', 'VD_ENV_WORKSPACE') }}"

    # password must be hashed, see below
    password:  "pass"
    nopass:    "stack ALL=(ALL) NOPASSWD:ALL"

  tasks: 

    - name: Upgrade all packages
      yum: name=* state=latest

    - name: Install relevant packages
      yum: name={{ item }} state=present
      with_items:
        - vim
        - git
        - net-tools
      become: yes
      become_user: root

    - name: Ensure 'stack' user is created
      user: name=stack
            shell=/bin/bash
            append=yes 
            state=present 
            password={{ password |password_hash('sha512') }} 

    - name: Ensure 'stack' user can execute passwordless commands
      lineinfile: dest=/etc/sudoers
                  line="{{ nopass }}"
                  state=present

    - name: Ensure work directories are present
      file: path="/opt/{{ item }}"
            owner=stack
            state=directory 
            mode="u=rwx,g=rx,o=rx"
      with_items:
        - devstack
        - stack

    - name: Clone devstack
      git: repo=https://git.openstack.org/openstack-dev/devstack
           dest=/opt/devstack
      become: yes
      become_user: stack
    
    - name: Add ssh key
      authorized_key: user=stack key="{{ key }}"

    - name: Copy minimal configuration for devstack
      copy: src="{{ workspace }}/local.conf" 
            dest=/opt/devstack/local.conf 
            owner=stack 
            group=stack 
            mode=0755
