---
- name: Play that provisions the guest VM environment for devstack
  
  hosts: 127.0.0.1
  connection: local

  vars:
    password:  "pass"
    nopass:    "stack ALL=(ALL) NOPASSWD:ALL"

  tasks: 

    - name: Ensure 'stack' user is created
      user: name=stack
            shell=/bin/bash
            append=yes 
            state=present 
            password={{ password |password_hash('sha512') }} 
      become: yes
      become_user: root

    - name: Ensure 'stack' user can execute passwordless commands
      lineinfile: dest=/etc/sudoers
                  line="{{ nopass }}"
                  state=present
      become: yes
      become_user: root

    - name: Ensure work directories are present
      file: path="/opt/{{ item }}"
            owner=stack
            group=stack
            state=directory 
            mode="u=rwx,g=rx,o=rx"
      with_items:
        - devstack
        - stack
      become: yes
      become_user: root

    - name: Ensure log directory is present
      file: path="/opt/stack/logs"
            owner=stack
            group=stack
            state=directory
            mode="u=rwx,g=rx,o=rx"
      become: yes
      become_user: root
