---
- name: Play that provisions the guest VM environment for devstack
  
  hosts: 127.0.0.1
  connection: local

  vars:
    password:  "pass"
    nopass:    "stack ALL=(ALL) NOPASSWD:ALL"

  tasks: 

    - name: Upgrade all packages
      yum: name=* state=latest

    - name: Install relevant packages
      yum: name={{ item }} state=present
      with_items:
        - vim
        - git
        - net-tools
      become: yes
      become_user: root

    - name: Ensure 'stack' user is created
      user: name=stack
            shell=/bin/bash
            append=yes 
            state=present 
            password={{ password |password_hash('sha512') }} 
      become: yes
      become_user: root

    - name: Ensure 'stack' user can execute passwordless commands
      lineinfile: dest=/etc/sudoers
                  line="{{ nopass }}"
                  state=present
      become: yes
      become_user: root

    - name: Ensure work directories are present
      file: path="/opt/{{ item }}"
            owner=stack
            state=directory 
            mode="u=rwx,g=rx,o=rx"
      with_items:
        - devstack
        - stack
      become: yes
      become_user: root

    - name: Clone devstack
      git: repo=https://git.openstack.org/openstack-dev/devstack
           dest=/opt/devstack
      become: yes
      become_user: stack
    
    - name: Copy minimal configuration for devstack
      copy: src="/opt/setup/local.conf" 
            dest=/opt/devstack/local.conf 
            owner=stack 
            group=stack 
            mode=0755
      become: yes
      become_user: root
