---
- name: Play that provisions the guest VM environment for devstack
  hosts: guests
  remote_user: root

  vars:
    # password must be hashed, see below
    password: pass
    nopass:   "stack ALL=(ALL) NOPASSWD:ALL"
  tasks: 

    - name: Upgrade all packages
      yum: name=* state=latest

    - name: Install relevant packages
      yum: name={{item}} state=present
      with_items:
        - sudo
        - vim
        - git
        - net-tools

    - name: Ensure 'stack' user is created
      user: name=stack
            shell=/bin/bash
            append=yes 
            state=present 
            password={{ password |password_hash('sha512') }} 

    - name: Ensure 'stack' user can execute passwordless commands
      lineinfile: dest=/etc/sudoers
                  line="{{ nopass }}"
                  state=present

    - name: Ensure '/opt/devstack' is present
      file: path=/opt/devstack
            owner=stack
            state=directory 
            mode="u=rwx,g=rx,o=rx"

    - name: Clone devstack
      git: repo=https://git.openstack.org/openstack-dev/devstack
           dest=/opt/devstack
      become: yes
      become_user: stack

    - name: Copy minimal configuration for devstack
      copy: src=local.conf 
            dest=/opt/devstack/local.conf 
            owner=stack 
            group=stack 
            mode=0755
