---
- name: Play that provisions the guest VM environment for devstack
  
  hosts: all
  connection: local

  vars:
    password:  "pass"
    nopass:    "stack ALL=(ALL) NOPASSWD:ALL"

  tasks: 

    - name: Ensure 'stack' user is created
      user: name=stack
            uid=1001
            shell=/bin/bash
            append=yes 
            state=present 
            password={{ password |password_hash('sha512') }} 
      become: yes
      become_user: root

    - name: Ensure 'stack' user can execute passwordless commands
      lineinfile: dest=/etc/sudoers
                  line="{{ nopass }}"
                  state=present
      become: yes
      become_user: root

    - name: Ensure 'stack' user can execute passwordless commands
      lineinfile: dest=/etc/sudoers
                  line="{{ nopass }}"
                  state=present
      become: yes
      become_user: root

