---
user:            "{{ lookup('env', 'USER') }}"
home:            "{{ lookup('env', 'HOME')}}"
host_ip:         "172.18.161.6"
hostname:        "devstack-box"
devstack_mount:  "devstack-box:/opt/devstack" 
stack_mount:     "devstack-box:/opt/stack"
ssh_config:      "{{ home }}/.ssh/config"
ssh_known_hosts: "{{ home }}/.ssh/known_hosts"
rsa_key:         "{{ home }}/.ssh/id_rsa.pub"
workspace:/home/Brian/Workspace/OpenSource/devstack-env
