---
- name: Ensure folders exist on the host

  hosts: 127.0.0.1
  connection: local

  vars:

    user:      "{{ lookup('env', 'USER') }}"
    workspace: "{{ lookup('env', 'VD_ENV_WORKSPACE') }}"

  tasks: 

    - name: "Create directories" 
      file: path="{{ workspace }}/{{ item }}"
            state=directory
      with_items:
        - devstack
        - src
      become: yes
      become_user: "{{ user }}"