---
- name: Play that does post-provisioning configuration on the host
  
  hosts: 127.0.0.1
  connection: local
  remote_user: root

  vars:

    ip:   "{{ lookup('env', 'VD_ENV_GUEST_IP')        }}"
    host: "{{ lookup('env', 'VD_ENV_HOSTNAME')        }}"
    key:  "{{ lookup('env', 'VD_ENV_DEFAULT_RSA_KEY') }}"
    dmnt: "{{ lookup('env', 'VD_ENV_DEVSTACK_MOUNT')  }}"
    smnt: "{{ lookup('env', 'VD_ENV_STACK_MOUNT')     }}"

    ssh_config:  "{{ lookup('env', 'VD_ENV_SSH_CONFIG')      }}"
    known_hosts: "{{ lookup('env', 'VD_ENV_SSH_KNOWN_HOSTS') }}"
    workspace:   "{{ lookup('env', 'VD_ENV_WORKSPACE')       }}"

  tasks:

    - name: "Add '{{ host }}' config to '{{ ssh_config }}'"
      blockinfile:
        dest: "{{ ssh_config }}"
        block: |
          Host {{ host }}                          
            Hostname     {{ ip }}            
            User         stack
            IdentityFile {{ key }}
        state: present

    - name: "Ensure '{{ known_hosts }}' is clean"
      lineinfile: dest="{{ known_hosts }}" 
                  regexp="^({{ ip }}|{{ host }})"
                  state=absent

    - name: "Remove old mounts in {{ workspace }}"
      mount: name="{{ workspace }}/{{ item }}"
             src=none
             fstype=none
             state=unmounted
      with_items:
        - devstack
        - stack

    - name: "Mount|Remount directories in {{ workspace }}"
      shell: "sshfs {{ host }}:{{ item.mount }} {{ workspace }}/{{ item.folder }}"
      with_items:
        - { mount: '{{ dmnt }}', folder: 'devstack' }
        - { mount: '{{ smnt }}', folder: 'stack'    }                                                              