---
- name: Post-provisioning configuration on host
  
  hosts: 127.0.0.1
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"

  sudo: true

  vars:

    ip:   "{{ lookup('env', 'VD_ENV_GUEST_IP')        }}"
    key:  "{{ lookup('env', 'VD_ENV_DEFAULT_RSA_KEY') }}"
    host: "{{ lookup('env', 'VD_ENV_HOSTNAME')        }}"
    dmnt: "{{ lookup('env', 'VD_ENV_DEVSTACK_MOUNT')  }}"
    smnt: "{{ lookup('env', 'VD_ENV_STACK_MOUNT')     }}"

    ssh_config:  "{{ lookup('env', 'VD_ENV_SSH_CONFIG')      }}"
    known_hosts: "{{ lookup('env', 'VD_ENV_SSH_KNOWN_HOSTS') }}"
    workspace:   "{{ lookup('env', 'VD_ENV_WORKSPACE')       }}"

  tasks:

    - name: "Add '{{ host }}' config to '{{ ssh_config }}'"
      blockinfile:
        dest: "{{ ssh_config }}"
        block: |
          Host {{ host }}                          
            Hostname     {{ ip }}            
            User         stack
            IdentityFile {{ key }}
            StrictHostKeyChecking no
        state: present

    - name: "Ensure '{{ known_hosts }}' is clean"
      lineinfile: dest="{{ known_hosts }}" 
                  regexp="^({{ ip }}|{{ host }})"
                  state=absent

    - name: "Check if unmount directories in {{ workspace }} is needed"
      shell: "fusermount -u {{ workspace }}/{{ item }}"
      with_items:
        - devstack
        - stack
      ignore_errors: yes

    - name: "Mount directories in {{ workspace }}"
      shell: "sshfs {{ host }}:{{ item.mount }} {{ workspace }}/{{ item.folder }}"
      with_items:
        - { mount: '{{ dmnt }}', folder: 'devstack' }
        - { mount: '{{ smnt }}', folder: 'stack'    }                                                               