---
- name: Play that does post-provisioning configuration on the host
  
  hosts: 127.0.0.1
  connection: local
  remote_user: root

  vars:

    user:      "{{ lookup('env', 'USER') }}"
    workspace: "{{ lookup('env', 'VD_ENV_WORKSPACE') }}"
    hostname:  "{{ lookup('env', 'VD_ENV_HOSTNAME')}}"

    ssh_config: "{{ lookup('env', ) }}"
    rsa_key:    "{{ lookup('env', 'VD_ENV_HOSTNAME')}}"

  tasks:

    - name:   
