---
- name: Play that does pre-provisioning configuration on the host
  hosts: 127.0.0.1
  connection: local
  remote_user: root

  tasks: 

    - name: Export all environment variables
      shell: bash /home/Brian/Workspace/OpenSource/devstack-env/environment

    - name: Output the current user
      debug: msg="current user is '{{ lookup('env', 'USER') }}'"

    - name: Output the current workspace
      debug: msg="current workspace is '{{ lookup('env', 'VAGRANT_DEVSTACK_WORKSPACE') }}'"
    
    - name: Create a test file 
      file: path=/opt/stupid_test_file 
            state=touch 
            owner={{ lookup('env', 'USER') }}
            mode=0777

    - name: Install relevant packages on host
      yum: name={{item}} state=present
      with_items:
        - sudo
        - sshfs


