---
- name: Play that does pre-provisioning configuration on the host

  hosts: 127.0.0.1
  connection: local
  remote_user: "{{ lookup('env', 'USER') }}"

  sudo: true

  vars:

    user:      "{{ lookup('env', 'USER') }}"
    workspace: "{{ lookup('env', 'VD_ENV_WORKSPACE') }}"
    guest_ip:  "{{ lookup('env', 'VD_ENV_GUEST_IP') }}"

  tasks: 

    - name: Create .env file for Vagrant 
      file: path="{{ workspace }}/.env"
            state=touch
      become: yes
      become_user: "{{ user }}"
    
    - name: Configure .env file for Vagrant
      blockinfile:
        dest: "{{ workspace }}/.env"
        block: |
          GUEST_IP={{ guest_ip }}

    - name: "Create '{{ workspace }}/devstack'" 
      file: path="{{ workspace }}/{{ item }}"
            state=directory
      with_items:
        - devstack
        - stack
      become: yes
      become_user: "{{ user }}"

    - name: Install relevant packages on host
      yum: name={{ item }} state=present
      with_items:
        - sudo
        - sshfs