---
- name: Play that does pre-provisioning configuration on the host
  hosts: 127.0.0.1
  connection: local
  remote_user: root

  vars:
    user:            "{{ lookup('env', 'USER') }}"
    home:            "{{ lookup('env', 'HOME') }}"
    host_ip:         "172.18.161.6"
    hostname:        "devstack-box"
    devstack_mount:  "devstack-box:/opt/devstack" 
    stack_mount:     "devstack-box:/opt/stack"
    ssh_config:      "{{ home }}/.ssh/config"
    ssh_known_hosts: "{{ home }}/.ssh/known_hosts"
    rsa_key:         "{{ home }}/.ssh/id_rsa.pub"
    workspace:       "/home/Brian/Workspace/OpenSource/devstack-env"

  tasks: 

    - name: Determine workspace 
      command: pwd
      register: working

    - name: Output the current user
      debug: msg="current user is '{{ user }}'"

    - name: Output the ssh config file
      debug: msg="current ssh config '' "

    - name: Output the current workspace
      debug: msg="current workspace is {{ workspace }}"
    
    - name: Create a test file 
      file: path=/opt/stupid_test_file 
            state=touch 
            owner={{ lookup('env', 'USER') }}
            mode=0777

    - name: Install relevant packages on host
      yum: name={{ item }} state=present
      with_items:
        - sudo
        - sshfs


