---
- name: Play that does pre-provisioning configuration on the host

  hosts: 127.0.0.1
  connection: local
  remote_user: root

  vars:

    user:      "{{ lookup('env', 'USER') }}"
    workspace: "{{ lookup('env', 'VD_ENV_WORKSPACE') }}"
    guest_ip:  "{{ lookup('env', 'VD_ENV_GUEST_IP') }}"

  tasks: 

    - name: Create .env file for Vagrant 
      file: path="{{ workspace }}/.env"
            state=touch
      become: yes
      become_user: "{{ user }}"
    
    - name: Configure .env file for Vagrant
      blockinfile:
        dest: "{{ workspace }}/.env"
        block: |
          GUEST_IP={{ guest_ip }}

    - name: Create devstack directory where devstack on the VM will be mounted 
      file: path="{{ workspace }}/devstack"
            state=directory
      become: yes
      become_user: "{{ user }}"

    - name: Create stack directory where the stack source on the VM will be mounted
      file: path="{{ workspace }}/stack"
            state=directory
      become: yes
      become_user: "{{ user }}"

    - name: Install relevant packages on host
      yum: name={{ item }} state=present
      with_items:
        - sudo
        - sshfs