---
- name: 

  hosts: 127.0.0.1
  connection: local

  vars:

    user:      "{{ lookup('env', 'USER') }}"
    workspace: "{{ lookup('env', 'WORKSPACE') }}"
    base_dir:  "{{ lookup('env', 'DEVSTACK_BASE_DIR') }}"
    base_img:  "{{ lookup('env', 'DEVSTACK_BASE_IMG')}}"
    dstk_img:  "{{ lookup('env', 'DEVSTACK_IMG')}}"

    dstk_container: "{{ lookup('env', 'DEVSTACK_CONTAINER') }}"

  tasks:
    
    - name: Stop the container, ignore errors if it has already stopped
      shell: "docker stop {{ dstk_container }}"
      ignore_errors: yes
      become: yes
      become_user: "{{ user }}"    
    
    - name: Remove the container, ignore errors if it is not there
      shell: "docker rm -f {{ dstk_container }}"
      ignore_errors: yes
      become: yes
      become_user: "{{ user }}"

    - name: Rebuild base Centos 7 image with systemd
      shell: "docker build -f {{ workspace }}/{{ base_dir }}/Dockerfile
                           --rm 
                           -t {{ base_img }} {{ base_dir }}"
      become: yes
      become_user: "{{ user }}"

    # - name: Rebuild Devstack image
    #   shell: "docker build -f {{ workspace }}/Dockerfile
    #                        --rm 
    #                        -t {{ dstk_img }} ."
    #   become: yes
    #   become_user: "{{ user }}"

    - name: Rebuild Devstack image
      shell: "docker-compose build"
      become: yes
      become_user: "{{ user }}"
