---
- name: 

  hosts: 127.0.0.1
  connection: local

  vars:

    user:           "{{ lookup('env', 'USER') }}"
    dstk_container: "{{ lookup('env', 'DEVSTACK_CONTAINER') }}"

  tasks:
    
    - name: Stop the container, ignore errors if it has already stopped
      shell: "docker stop {{ dstk_container }}"
      ignore_errors: yes
      become: yes
      become_user: "{{ user }}"    
    
    - name: Remove the container, ignore errors if it is not there
      shell: "docker rm -f {{ dstk_container }}"
      ignore_errors: yes
      become: yes
      become_user: "{{ user }}"
