---
- name: Ensure folders exist on the host

  hosts: 127.0.0.1
  connection: local

  vars:

    user:      "{{ lookup('env', 'USER') }}"
    workspace: "{{ lookup('env', 'WORKSPACE') }}"

  tasks: 

    - name: Ensure work directories are present
      file: path="{{ workspace }}/{{ item }}"
            state=directory 
      with_items:
        - devstack
        - src
      become: yes
      become_user: "{{ user }}"

    - name: Clone devstack
      git: repo=https://git.openstack.org/openstack-dev/devstack
           dest="{{ workspace }}/devstack"
