---
- name: Create folders and make sure devstack repo is pulled

  hosts: 127.0.0.1
  connection: local

  vars:

    user:      "{{ lookup('env', 'USER') }}"
    workspace: "{{ lookup('env', 'WORKSPACE') }}"

  tasks: 

    - name: Ensure source mount point present
      file: path="{{ workspace }}/src"
            state=directory
            mode="u=rwx,g=rwx,o=rx" 
      become: yes
      become_user: "{{ user }}"

    - name: Ensure devsack directory are present
      file: path="{{ workspace }}/src/devstack"
            state=directory
            mode="u=rwx,g=rwx,o=rx"
      become: yes
      become_user: "{{ user }}"

    - name: Ensure devsack directory are present
      file: path="{{ workspace }}/src/stack"
            state=directory
            mode="u=rwx,g=rwx,o=rx"
      become: yes
      become_user: "{{ user }}"

    - name: Clone devstack
      git: repo=https://git.openstack.org/openstack-dev/devstack
           dest="{{ workspace }}/src/devstack"
